baseURL = "https://tranquil-puffpuff-e6e7a3.netlify.app/"
languageCode = "pt-br"
title = "Grupo Kwanza"

theme = "beautifulhugo"

enableRobotsTXT = true
canonifyURLs = false
relativeURLs = false

[pagination]
  pagerSize = 10

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "equipe"
    name = "Identidade Kwanza"
    url = "/equipe-kwanza/"
    weight = 2

  [[menu.main]]
    identifier = "guia"
    name = "Guia do Capoeirista Kwanza"
    url = "/guia-do-capoeirista-kwanza/"
    weight = 3

  [[menu.main]]
    identifier = "vem_aprender"
    name = "Vem Aprender"
    url = "/vem-aprender/"
    weight = 4

  [[menu.main]]
    identifier = "calendario"
    name = "Calend√°rio"
    url = "/calendario-kwanza/"
    weight = 5

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 6

  [[menu.main]]
    identifier = "contatos"
    name = "Contatos"
    url = "/contatos/"
    weight = 7

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
